
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: weatherology_development

test:
  <<: *default
  database: weatherology_test

production:
  <<: *default
  database: weatherology_production
  username: weatherology
  password: <%= ENV['WEATHEROLOGY_DATABASE_PASSWORD'] %>
